apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: synapse-

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml


configMapGenerator:
  - name: synapse-config
    files:
      - homeserver.yaml
      - log.config

secretGenerator:
  - name: synapse-signing-key
    files:
      - synapse_signing_key