apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3

  bootstrap:
    initdb:
      database: chat
      owner: chat
      secret:
        name: chat-postgres-sec

  storage:
    storageClass: managed-csi-premium
    size: 2Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: chat-postgres-sec-super

  postgresql:
    parameters:
      shared_buffers: "128MB"

  resources:
    requests:
      memory: "512Gi"
      cpu: "20m"
