apiVersion: v1
kind: Secret
metadata:
    name: sec-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:C2BMb4X17HGeHL8T6FT2rpXW9hg=,iv:dtxgivCnLl76bCi/uA5dG9e5hY+EOc6fmjTlIHBe0Wg=,tag:udx2p0jq/QjOfajIECNl3g==,type:str]
    username: ENC[AES256_GCM,data:zHLGr/Yqs6o=,iv:nOuUubUgZTeuNx8ifJ5uq+0YUo+q2RCJ1zZ4tQXYKoU=,tag:oCwuvTnDo511mbuuVI7ahw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcUxmaEdCcitwV1VnVG5U
            ZC9RNnNmVUZib3plZjNsb21nY0g5WUw5YlZvCi9NK3V1OWdNSEwxWkdpYWc0c2Jo
            TzF6ZmJ5bm0rbWhWME1QbjRUcXlBZHMKLS0tIERjWmNoTTY1ZDF5VVJSSDVxaEdQ
            MGUvUHhPUWJRbnNVeTl5Z2VJaWthblUK1XAy4+4ID0WRTwxBSpnNkYIdP+E9dfp/
            1UcAD616R9cjby5MSTlU7AH8iscHi6k0ieyhI6PHejJJA50i7gcwew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T19:58:33Z"
    mac: ENC[AES256_GCM,data:+Lwl//OSDZOf1zW74//vRXyqWggRnEyCftkKn7+0LVohybLcM+lGT+0hwQ198XFRnUT1tIqc3UQU0ljwc99o611hQqDfZXh1ZimnSvLFjB6YXJEUOBolFcpYUNnzeoYHgozYTmrbcOWjlQkBkgIzKbwiNWpNjS9BF9gMst8YLX8=,iv:nlgw/TwudRULwTwmd8SMBsvYTPTf1T8dfJyahfCVz6w=,tag:59yafdRxW8SQfNLKL5eGTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
