apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:X+lEGb1/PhMLlSjFEnY6W7iZD6k=,iv:WAm1/j83lhwH54NkSQU0YGCERahxGfectfb2MiKhJVE=,tag:yfu8paDTEiuXZLCpVwy+sA==,type:str]
    username: ENC[AES256_GCM,data:3KpHFQ==,iv:O8FZdhcDJjLsXho2vHaxAUt+DVsgQIahuaVMGaxC/Hk=,tag:KDbr9bXvHgpOsx/FBqFlJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcWM2aDA5cm5HajNnSmNx
            OFBLT2FTcFRuVDQrS0ZiSGFwL2poMXQvdTIwCk1TbUhaUGNPL1ZtV0t6UUhZZ25z
            Ry95b0VsYzNsN2NLZ2M3N0xrd1JIWVkKLS0tIGRaZGpLUm8xbEVUV2Q2VHI4c0tT
            M1V4cDNkWE5jNW15b2hiL2EvNDd0clEKg0N1dXJ0TBrPPl/I/GsympjbBskyKBRq
            ejfV/ma7kdZo49mtChO/eilPxkNoyOhsltHzMKTVaa82q0d44kmKbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T19:58:44Z"
    mac: ENC[AES256_GCM,data:Q1gBidXz8a2RhN2qBaTix2uabvQV/GK7SxteKXmK9+YDN3WcSDWBKy7JVqIKRdqSI3EjEi6yVq/YGWF0tLlH2Pc1YPC1qASOaB7j7tfZaaRAXAoAbXtBvWQmNsV6rwWJF0DaR1GDszAT4CKwol07Zz+bJedI7mgadXPeuYngHYA=,iv:TB0vZciZLsjqNYmr0rFuTW9aAaR+pcu9CYefoSdP0y4=,tag:T4TL5QFPwY8TieNztpNJzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
