apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    LIVEKIT_KEY: ENC[AES256_GCM,data:Uikj9Z5nqc+TMzcj4XZc,iv:Us0mgk8JmjLMZSQwM6Bp+mTwqFkbTAOtGVQsw/FpZ64=,tag:GSdDwZMy4RmvN86BqEVEyg==,type:str]
    LIVEKIT_SECRET: ENC[AES256_GCM,data:SqbHCXVpbi67E5BiMvn3HtSVu3KJIXY0G5bPhBulZtKiBhierdpwUOcnXYY=,iv:we3fNR2pZYNaGhpE+3ZRSH0Trrc2r3LYuUmiZsT6jSE=,tag:LOsOgKNUYUP7yF9QdmUl0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcVRCSWJKcDU4SWZNakd6
            cy9PSnB4M3QyRG91UHVsNTZYT0JhSG5EOVJnCkpLQjdOL0hhTVJ5clZER0NmN3B3
            ZlQ1dllxVnJqZ3lIeDhERG5sRVpOQTgKLS0tIHZrYXdhSGx4UDQvRDU4VkEwVWkr
            NW5aTEJtaFpOaG1xVDZVeldaWXhYc0EKZKOnAUwcnQWp3hHmHImNPtz0nzjPgMTd
            fYobLJTJT+IjtEBIRLnsy8CaHm94dfUJ5GzMC/wj4Vg5Q/q5mzsn1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T07:56:41Z"
    mac: ENC[AES256_GCM,data:YJQV+MA0Xx7MKyEr20yiKJEmx2v41oSyYQxM4UcJtO+AQ4n5H+rPP3bnr5hWmCDTlaTjVL8Kz1xmY+BayZUTIroonnjjYgj097focCtF0Ak7FDxnopzeglXlPf9Zj3Wbnu3UrjzTdgdNbAF/i74oEztPA0Nw79LlV9lAc06pujk=,iv:GiUINroQikUbk5BLjtRs9lvbnlJMXyD+U8/Q0LfZXbI=,tag:Mm8F/PHGWLQ342LiZ7Y5Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
